class aix_tunables::ioo($aio_maxreqs                    = undef,
                        $aio_maxservers                 = undef,
                        $aio_minservers                 = undef,
                        $aio_server_inactivity          = undef,
                        $j2_atimeupdatesymlink          = undef,
                        $j2_dynamicbufferpreallocation  = undef,
                        $j2_inodecachesize              = undef,
                        $j2_maxpagereadahead            = undef,
                        $j2_maxrandomwrite              = undef,
                        $j2_metadatacachesize           = undef,
                        $j2_minpagereadahead            = undef,
                        $j2_npagesperwritebehindcluster = undef,
                        $j2_nrandomcluster              = undef,
                        $j2_recoverymode                = undef,
                        $j2_syncpagecount               = undef,
                        $j2_syncpagelimit               = undef,
                        $lvm_bufcnt                     = undef,
                        $maxpgahead                     = undef,
                        $maxrandwrt                     = undef,
                        $numclust                       = undef,
                        $numfsbufs                      = undef,
                        $pd_npages                      = undef,
                        $posix_aio_active               = undef,
                        $posix_aio_maxreqs              = undef,
                        $posix_aio_maxservers           = undef,
                        $posix_aio_minservers           = undef,
                        $posix_aio_server_inactivity    = undef,
                        $enforce_default                = undef,) {


  ioo {'ioo':
    aio_maxreqs                    => $aio_maxreqs,
    aio_maxservers                 => $aio_minservers,
    aio_minservers                 => $aio_server_inactivity,
    aio_server_inactivity          => $aio_server_inactivity,
    j2_atimeupdatesymlink          => $j2_atimeupdatesymlink,
    j2_dynamicbufferpreallocation  => $j2_dynamicbufferpreallocation,
    j2_inodecachesize              => $j2_inodecachesize,
    j2_maxpagereadahead            => $j2_maxpagereadahead,
    j2_maxrandomwrite              => $j2_maxrandomwrite,
    j2_metadatacachesize           => $j2_metadatacachesize,
    j2_minpagereadahead            => $j2_minpagereadahead,
    j2_npagesperwritebehindcluster => $j2_npagesperwritebehindcluster,
    j2_nrandomcluster              => $j2_nrandomcluster,
    j2_recoverymode                => $j2_recoverymode,
    j2_syncpagecount               => $j2_syncpagecount,
    j2_syncpagelimit               => $j2_syncpagelimit,
    lvm_bufcnt                     => $lvm_bufcnt,
    maxpgahead                     => $maxpgahead,
    maxrandwrt                     => $maxrandwrt,
    numclust                       => $numclust,
    numfsbufs                      => $numfsbufs,
    pd_npages                      => $pd_npages,
    posix_aio_active               => $posix_aio_active,
    posix_aio_maxreqs              => $posix_aio_maxreqs,
    posix_aio_maxservers           => $posix_aio_maxservers,
    posix_aio_minservers           => $posix_aio_minservers,
    posix_aio_server_inactivity    => $posix_aio_server_inactivity,
    enforce_default                => $enforce_default,
  }

}

