# Class for schedo kernel tunable
class aix_tunables::schedo( $affinity_lim                  = undef,
                            $big_tick_size                 = undef,
                            $ded_cpu_donate_thresh         = undef,
                            $fixed_pri_global              = undef,
                            $force_grq                     = undef,
                            $maxspin                       = undef,
                            $pacefork                      = undef,
                            $proc_disk_stats               = undef,
                            $sched_d                       = undef,
                            $sched_r                       = undef,
                            $tb_balance_s0                 = undef,
                            $tb_balance_s1                 = undef,
                            $tb_threshold                  = undef,
                            $timeslice                     = undef,
                            $vpm_fold_policy               = undef,
                            $vpm_throughput_core_threshold = undef,
                            $vpm_throughput_mode           = undef,
                            $vpm_xvcpus                    = undef,
                            $enforce_default               = undef,){

  schedo {'schedo':
    affinity_lim                  => $affinity_lim,
    big_tick_size                 => $big_tick_size,
    ded_cpu_donate_thresh         => $ded_cpu_donate_thresh,
    fixed_pri_global              => $fixed_pri_global,
    force_grq                     => $force_grq,
    maxspin                       => $maxspin,
    pacefork                      => $pacefork,
    proc_disk_stats               => $proc_disk_stats,
    sched_d                       => $sched_d,
    sched_r                       => $sched_r,
    tb_balance_s0                 => $tb_balance_s0,
    tb_balance_s1                 => $tb_balance_s1,
    tb_threshold                  => $tb_threshold,
    timeslice                     => $timeslice,
    vpm_fold_policy               => $vpm_fold_policy,
    vpm_throughput_core_threshold => $vpm_throughput_core_threshold,
    vpm_throughput_mode           => $vpm_throughput_mode,
    vpm_xvcpus                    => $vpm_xvcpus,
    enforce_default               => $enforce_default,
  }

}
